default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV.fetch("EASYBOT_DATABASE_PASSWORD")%>
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: EasyBot_development

test:
  <<: *default
  database: EasyBot_test

production:
  <<: *default
  database: EasyBot_production
  username: EasyBot
  password: <%= ENV.fetch("EASYBOT_DATABASE_PASSWORD") %>
